//
// Created by mauro on 13/03/2024.
//

#ifndef PROJECT_SOFTWAREENGINEERING_INPUTTEST_H
#define PROJECT_SOFTWAREENGINEERING_INPUTTEST_H


class InputTest {

};


#endif //PROJECT_SOFTWAREENGINEERING_INPUTTEST_H
