//
// Created by mauro on 13/03/2024.
//
#include <iostream>
#ifndef PROJECT_SOFTWAREENGINEERING_PRINTINGSYSTEMUTILS_H
#define PROJECT_SOFTWAREENGINEERING_PRINTINGSYSTEMUTILS_H

#endif //PROJECT_SOFTWAREENGINEERING_PRINTINGSYSTEMUTILS_H
bool isNumber(std::string& s);